# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 22:18
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formPicture', models.BooleanField()),
                ('formAge', models.BooleanField()),
                ('formEducation', models.BooleanField()),
                ('formPlaceOfResidence', models.BooleanField()),
                ('formAboutYou', models.BooleanField()),
                ('formCurrentStatus', models.BooleanField()),
                ('formLanguages', models.BooleanField()),
                ('formExperience', models.BooleanField()),
                ('formHobby', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='media/avatars')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('education', models.CharField(choices=[('Secondary Education', 'secondary education'), ('Bachelor Degree', 'bachelor degree'), ('Master Degree', 'master degree'), ('Engineer', 'engineer'), ('Other', 'other')], max_length=50)),
                ('placeOfResidence', models.CharField(max_length=120)),
                ('aboutYou', models.CharField(max_length=1000)),
                ('currentStatus', models.CharField(choices=[('Student', 'student'), ('Working - The same industry', 'working - the same industry'), ('Working - Other industry', 'working - other industry'), ('Unemployed', 'unemployed')], max_length=50)),
                ('languages', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=1000)),
                ('hobby', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('Accounting', 'accounting'), ('Factory', 'factory'), ('Banking', 'banking'), ('Marketing', 'marketing'), ('IT - Software Development', 'it - software development'), ('IT - Administration', 'it - administration'), ('Transport', 'transport'), ('Medical', 'medical'), ('Education', 'education'), ('Hospitality', 'hospitality'), ('Real Estate', 'real estate'), ('Production', 'production'), ('Engineering', 'engineering'), ('Other', 'other')], max_length=50)),
                ('avatar', models.ImageField(upload_to='media/avatars')),
                ('title', models.CharField(max_length=70)),
                ('aboutUs', models.CharField(max_length=2000)),
                ('requirements', models.CharField(max_length=500)),
                ('whatWeOffer', models.CharField(max_length=500)),
                ('salary', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=120)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_offer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.JobOffer'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationrequirements',
            name='job_offer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.JobOffer'),
        ),
    ]
