# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 17:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='aboutYou',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='currentStatus',
            field=models.CharField(blank=True, choices=[('Student', 'student'), ('Working - The same industry', 'working - the same industry'), ('Working - Other industry', 'working - other industry'), ('Unemployed', 'unemployed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='education',
            field=models.CharField(blank=True, choices=[('Secondary Education', 'secondary education'), ('Bachelor Degree', 'bachelor degree'), ('Master Degree', 'master degree'), ('Engineer', 'engineer'), ('Other', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='hobby',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='placeOfResidence',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
