# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20171229_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='jobDescription',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
