# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_joboffer_jobdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
