# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobapplication_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='currentStatus',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Working - the same industry', 'Working - the same industry'), ('Working - other industry', 'Working - other industry'), ('Unemployed', 'Unemployed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='education',
            field=models.CharField(blank=True, choices=[('Secondary Education', 'Secondary Education'), ('Bachelor degree', 'Bachelor degree'), ('Master Degree', 'Master Degree'), ('Engineer', 'Engineer'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='industry',
            field=models.CharField(choices=[('Accounting', 'Accounting'), ('Factory', 'Factory'), ('Banking', 'Banking'), ('Marketing', 'Marketing'), ('IT - Software Development', 'IT - Software Development'), ('IT - Administration', 'IT - Administration'), ('Transport', 'Transport'), ('Medical', 'Medical'), ('Education', 'Education'), ('Hospitality', 'Hospitality'), ('Real Estate', 'Real Estate'), ('Production', 'Production'), ('Engineering', 'Engineering'), ('Other', 'Other')], max_length=50),
        ),
    ]
