# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20171231_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='hobby',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
