# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20171231_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='aboutYou',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
