# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20180102_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(max_length=38),
        ),
    ]
